//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportEntities : DbContext
    {
        public AirportEntities()
            : base("name=AirportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airoport> Airoport { get; set; }
        public virtual DbSet<Boss> Boss { get; set; }
        public virtual DbSet<CharterFlight> CharterFlight { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<FreightFlight> FreightFlight { get; set; }
        public virtual DbSet<Partition> Partition { get; set; }
        public virtual DbSet<Passenger1> Passenger1 { get; set; }
        public virtual DbSet<Passenger2> Passenger2 { get; set; }
        public virtual DbSet<PassengersFlight> PassengersFlight { get; set; }
        public virtual DbSet<Pilot> Pilot { get; set; }
        public virtual DbSet<Plane> Plane { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
