//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        public string PlaneNumber { get; set; }
        public string TypeP { get; set; }
        public string Maker { get; set; }
        public System.DateTime LatestReview { get; set; }
        public int FlightNumb { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
